name: WG_KeepInventoryFlag
main: me.atomiz.wgflags.Main
description: Allows you to set keep inventory in the different regions.
version: 1.0
api-version: 1.14
authors: [ Atomiz ]
depend: [ WorldGuard ]
softdepend: [ WorldEdit ]
website: http://atomix.000webhostapp.com/